### ISSUE TITLE
Backoffcoefficient can't be used as nullable double

### ISSUE THREAD

**Issue by sandromastronardi** [shibayan/durable-functions-typed-proxy#16]
Hi,

When trying to set the BackoffCoefficient to a retry attribute it gives an error in Visual Studio:
BackoffCoefficient is not a valid named attribute argument because it is not a valid attribute parameter type...
could this be because it's a nullable double? and how can I use this? I'm using .NET Core 3.1 but it isn't supported afaik.

https://stackoverflow.com/questions/1416126/why-is-a-nullablet-not-a-valid-custom-attribute-parameter-when-t-is

**Comment by shibayan** [comment]
Thanks for the feedback. I forgot that nullable cannot be used in attributes.

It will be fixed soon.

**Comment by shibayan** [comment]
v2.2.1 Released
